aws/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import *
from django.conf.urls.static import static #For img 
from django.conf import settings #For img
# For password reset email template to render html tags
from django.contrib.auth import views as auth_views

# handler404 = 'main.views.error_404_view'
from dashreporting.views import *
from django.urls import re_path

urlpatterns = [
    # For password reset email template to render html tags
    # path('accounts/password_reset/', auth_views.PasswordResetView.as_view(
    #     html_email_template_name='registration/password_reset_email.html'
    # )),

    path('accounts/', include('django.contrib.auth.urls')),

    path('admin/', admin.site.urls),

    path('', include('main.urls')),

    path('todo/', include('todo.urls')),
    path('quiz/', include('quiz.urls')),
    path('blog/', include('blog.urls')),
    path('shop/', include('shop.urls')),

    path('dash/', include('dashreporting.urls')),
    path('calendar/', include('calendar_app.urls')),

    path('login/', user_login, name="login"),
    path('logout/', user_logout, name="logout"),
    path('signup/', signup, name="signup"),
    # path('signup-done/', signup_done, name="signup_done"),
    path('change-password/', change_password, name="change-password"),

    path('ckeditor/', include('ckeditor_uploader.urls')), #for ckeditor

    # Django Dash Plotly 
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
    

] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT) #For img

blog/urls.py
from django.urls import path
from blog.views import *

# Define app name to call
app_name = "blog"

urlpatterns = [
    path('posts/', posts, name="posts"),
    path('post/<slug:slug>/', post, name='post'),

    path('post-list/', post_list, name="post_list"),
    path('post-create/', post_create, name="post_create"),    
    path('<slug:slug>/update/', post_update, name='post_update'),
    path('<int:id>/delete/', post_delete, name='post_delete'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import slugify
from django.db.models.signals import pre_save
import random
from ckeditor_uploader.fields import RichTextUploadingField #CKEditor

STATUS_CHOICES = ( 
   ('draft', 'Draft'), 
   ('published', 'Published'), 
) 

class Post(models.Model):
    user = models.ForeignKey(User, on_delete= models.CASCADE )
    title = models.CharField(max_length=250, null=True, blank=True)
    content = RichTextUploadingField(extra_plugins=['codesnippet'],null=True, blank = True) #CKEditor
    image = models.ImageField(upload_to='pictures/%Y/%m/%d/' , max_length=255, null=True, blank=True)
    slug = models.SlugField(unique = True, editable = False, max_length = 150)
    status = models.CharField(max_length = 10, choices = STATUS_CHOICES, default ='draft')
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now= True)

    class Meta: 
        ordering = ('-created_at', )

    def __str__(self): 
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post', kwargs={'slug': self.slug})

# Create unique slug .
def create_slug(instance, new_slug = None):
    slug = slugify(instance.title)     
    if new_slug is not None: 
        slug = new_slug 
    else: 
        slug = slugify(instance.title)

    qs = Post.objects.filter(slug = slug).order_by("-id")
    exists = qs.exists()
    if exists: 
        new_slug = "{slug}-{id}".format( slug = slug, id = qs.first().id)               
        return create_slug(instance, new_slug = new_slug) 
    return slug 

def pre_save_receiver(sender, instance, *args, **kwargs): 
   if not instance.slug: 
       instance.slug = create_slug(instance) 
    
pre_save.connect(pre_save_receiver, sender = Post) 

forms/post_create.py
from django.forms import ModelForm
from blog.models import Post

class PostCreateForm(ModelForm):

    class Meta:
        model = Post
        fields = [
            'title',
            'content',
            'status',
            'image'
        ]

blog/views.py
from django.shortcuts import render 
from blog.models import Post
from django.http import HttpResponse, HttpResponseRedirect
from forms.post_create import PostCreateForm
from django.contrib import messages
from django.urls import reverse
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger   #Pagination
from django.contrib.auth.decorators import login_required
from aws.role_decorator import role_required

# Frontend Section
def posts(request):
    context = {}
    post_list =Post.objects.filter( status = "Published").order_by('-created_at')

    #Pagination START
    page = request.GET.get('page')
    paginator = Paginator(post_list, 5)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    #Pagination END!
    context['posts'] = posts
    # SEARCH START
    query = request.GET.get('q')    
    if query:
        post_list = post_list.filter(
            Q(title__icontains = query) |
            Q(content__icontains = query)
        )
        context['posts'] = post_list
        return render(request, 'blog/posts.html', context)
    # SEARCH END !!!
    return render(request, 'blog/posts.html', context)

def post(request, slug):
    context = {}
    q = Post.objects.filter(slug__iexact = slug) 
    if q.exists():
        q = q.first() 
    else: 
        return HttpResponse('<h1>Post Not Found</h1>')
    context['post'] = q
    return render(request, 'blog/post.html', context)

# Backend Section
@login_required(login_url = "/login/")
@role_required(allowed_roles = ["admin", "visitor"])
def post_list(request):
    context = {}
    post_list = Post.objects.all()
    context['posts'] = post_list    
    return render(request, 'blog/post_list.html', context)

@login_required(login_url = "/login/")
@role_required(allowed_roles = ["admin"])
def post_create(request):
    context = {}
    user = request.user
    if request.method == "POST":
        try:
            form = PostCreateForm(request.POST, request.FILES)
            if form.is_valid():
                post_form = form.save(commit = False)
                post_form.user = user
                post_form.save()
            messages.success(request, "Your post has been successfully submitted.")
            return HttpResponseRedirect(reverse('blog:post_list'))
        except Exception as e:
            messages.warning(request, "There was a problem.")
            return render(request, 'blog/post_create.html', context)
    else:
        form = PostCreateForm()    
    context['form'] = form
    return render(request, 'blog/post_create.html', context)

@login_required(login_url = "/login/")
@role_required(allowed_roles = ["admin"])
def post_update(request, slug):
    context = {}
    user = request.user
    post = Post.objects.filter(slug = slug).first()
    if request.method == "POST":
        try:
            form = PostCreateForm(request.POST, request.FILES, instance=post)
            if form.is_valid():
                post_form = form.save(commit = False)
                post_form.user = user
                post_form.save()
            messages.success(request, "Your post has been successfully updated.")
            return HttpResponseRedirect(reverse('blog:post_list'))
        except Exception as e:
            messages.warning(request, "There was a problem.")
            return render(request, 'blog/post_update.html', context)
    else:
        form = PostCreateForm(instance = post)    
    context['form'] = form
    return render(request, 'blog/post_edit.html', context)

@login_required(login_url = "/login/")
@role_required(allowed_roles = ["admin"])
def post_delete(request, id):
    if request.method == "POST":
        id = id
        Post.objects.filter(id = id).delete()
        messages.success(request, "Successfully deleted ")
    return HttpResponseRedirect(reverse('blog:post_list'))

templates/blog/post.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'ckeditor/ckeditor/plugins/codesnippet/lib/highlight/styles/default.css' %}" />
{% endblock css %}

{% block content %}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            
          </div>
          <div class="col-sm-6">
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content pb-5">
        <div class="container">
            <div class="card card-body ">
                <div class=" row">
                    <div class="col-md-12">
                        <h2 class="text-muted">{{post.title | title}}</h2>
                        <small class="text-muted"><i class="far fa-calendar-alt"></i> {{post.created_at}} | <i class="fas fa-pen"></i> {{post.user.email}}</small><br> <br>
                        {% if post.image%}
                        <img src="{{post.image.url}}" alt="Product Image" >
                        {% endif %}
                        <div class="blog-post">
                          <p class="text-muted">
                          {{post.content | safe}}
                          </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- /.content -->
  </div>
{% endblock content %}

{% block javascript %}
<script src="{% static 'ckeditor/ckeditor/plugins/codesnippet/lib/highlight/highlight.pack.js' %}"></script>
<script>hljs.initHighlightingOnLoad();</script>
{% endblock javascript %}

templates/blog/post_create.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %} <!-- Crispy Forms --> 
{% block css %}

{% endblock css %}

{% block content %}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Post Create Form</h1>
          </div>
          <div class="col-sm-6">
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
      <div class="container">
        <div class="row">        
          <div class="col-md-10 ">
            <div class="card">
              <div class="card-body">
                <form action="" method="POST" enctype="multipart/form-data">
                  {% csrf_token %}
                  {{form | crispy}}
                  {{form.media}}
                  <button class="btn btn-primary float-right" type="submit">Submit</button>
                </form>
              </div>                
            </div>
          </div>
        </div>
      </div>        
    </section>
    <!-- /.content -->
  </div>
{% endblock content %}

{% block javascript %}

{% endblock javascript %}

templates/blog/post_edit.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %} <!-- Crispy Forms --> 
{% block css %}

{% endblock css %}

{% block content %}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Post Update Form</h1>
          </div>
          <div class="col-sm-6">
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
      <div class="container">
        <div class="row">       
          <div class="col-md-10 ">
            <div class="card">
              <div class="card-body">
                <form action="" method="POST" enctype="multipart/form-data">
                  {% csrf_token %}
                  {{form | crispy}}
                  {{form.media}}
                  <button class="btn btn-primary float-right" type="submit">Submit</button>
                </form>
              </div>                
            </div>
          </div>
        </div>
      </div>        
    </section>
    <!-- /.content -->
  </div>
{% endblock content %}

{% block javascript %}

{% endblock javascript %}

templates/blog/post_list.html
{% extends 'base.html' %}
{% load static %}
{% block css %}

{% endblock css %}

{% block content %}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Post List</h1>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
     <!-- Main content -->
     <section class="content">
      <div class="row">
        <div class="col-12">      
          <!-- /.card -->
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">Post List</h3>
              <div class="card-tools">
                <a href="{%  url 'blog:post_create' %}" class="btn btn-info float-right" ><i class="fas fa-plus"></i> Add New Post</a>
              </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <table id="example1" class="table table-striped">
                <thead>
                <tr>
                  <th>Title</th>
                  <th>Slug</th>
                  <th>Status</th>
                  <th>Created Date</th>
                  <th>Updated Date</th>
                  <th></th>
                </tr>
                </thead>
                <tbody>
                {% for post in posts %}
                <tr>
                  <td>{{post.title}}</td>
                  <td>{{post.slug}}</td>
                  <td>{{post.status}}</td>
                  <td>{{post.created_at | date:"d/m/Y"}} {{post.created_at | time:"H:i"}}</td> 
                  <td>{{post.updated_at | date:"d/m/Y"}} {{post.updated_at | time:"H:i"}}</td>                                 
                <td class="project-actions text-right">
                    <a class="btn btn-info btn-sm" href="{%  url 'blog:post_update' post.slug %}">
                        <i class="fas fa-pencil-alt">
                        </i>
                        Edit
                    </a>
                    <button class="btn btn-danger btn-sm" data-toggle="modal" data-target="#modal-default-delete-{{post.id}}">
                        <i class="fas fa-trash">
                        </i>
                        Delete
                    </button>
                    <!-- /. Delete modal -->
                    <form action="{%  url 'blog:post_delete' post.id %}" method="POST">
                      {% csrf_token %}
                    <div class="modal fade" id="modal-default-delete-{{post.id}}">
                      <div class="modal-dialog">
                        <div class="modal-content">
                          <div class="modal-header" style="border-bottom:none;">                    
                            <i class="fas fa-exclamation-circle fa-5x" style="margin:0 auto; color:#F8BB86;"></i>
                          </div>
                          <div class="modal-body text-muted" style="margin:0 auto;border-bottom:none;">
                              <h3 >Are you sure to Delete?</h3>
                          </div>
                          <div class="modal-footer justify-content-between">
                            <button type="button" class="btn btn-default" data-dismiss="modal">No, thanks</button>
                            <button type="submit" class="btn btn-primary">Yes, Delete it</button>
                          </div>
                        </div>
                        <!-- /.modal-content -->
                      </div>
                      <!-- /.modal-dialog -->
                    </div>
                    </form>
                </td>                
                {% endfor %}
                </tr>                
                </tbody>
                <tfoot>
                <tr>
                    <th>Title</th>
                    <th>Slug</th>
                    <th>Status</th>
                    <th>Created Date</th>
                    <th>Updated Date</th>
                    <th></th>
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
{% endblock content %}

{% block javascript %}
<!-- DataTables -->
<script src="{% static 'assets/plugins/datatables/jquery.dataTables.js' %} "></script>
<script src="{% static 'assets/plugins/datatables-bs4/js/dataTables.bootstrap4.js' %} "></script>
<!-- page script -->
<script>
  $(function () {
    $("#example1").DataTable();
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
    });
  });
</script>
{% endblock javascript %}

templates/blog/posts.html
{% extends 'base.html' %}
{% load static %}
{% block css %}

{% endblock css %}

{% block content %}
<div class="content-wrapper pb-5">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <!-- SEARCH FORM -->
        <div class="row  justify-content-center">
          <form class="form-inline ml-3" action="" method="GET">
            <div class="input-group input-group-sm">
              <input class="form-control form-control-navbar" name="q" type="search" placeholder="Search on blog" aria-label="Search">
              <div class="input-group-append">
                <button class="btn btn-navbar" id="blog-search" type="submit">
                  <i class="fas fa-search"></i>
                </button>
              </div>
            </div>
          </form>
        </div>        
      </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container ">         
            {% for post in posts %}
            <div class="card card-body">
                <div class=" row">
                    <div class="col-md-2">
                        {% if post.image%}
                          <img src="{{post.image.url}}" alt="Post Image" width="150px"  >
                        {% endif %}
                    </div>
                    <div class="col-md-10">
                        <a href="{{post.get_absolute_url}}" class="post-title"><h4>{{post.title}}</h4></a>
                        <small><i class="nav-icon fas fa-calendar-alt"></i> {{post.created_at | date:"d F Y"}} </small>
                        <div class="post-abstract">
                          <p class="text-muted">
                            {{post.content | safe | truncatewords:50}}
                          </p>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            <div class="card-footer clearfix justify-content-center">
              {% if posts.has_other_pages %}
                <ul class="pagination pagination-sm justify-content-center">
                  {% if posts.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{ posts.previous_page_number }}">&laquo;</a></li>
                  {% else %}
                    <li class="disabled page-item"><a class="page-link" href="#"><span>&laquo;</span></a></li>
                  {% endif %}
                  {% for i in posts.paginator.page_range %}
                    {% if posts.number == i %}
                      <li class="page-item active"><a class="page-link" href="#">{{ i }} </a><span class="sr-only">(current)</span></li>
                    {% else %}
                      <li lass="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                  {% endfor %}
                  {% if posts.has_next %}
                    <li lass="page-item"><a class="page-link" href="?page={{ posts.next_page_number }}">&raquo;</a></li>
                  {% else %}
                    <li class="disabled page-item"><a class="page-link" href="#"><span>&raquo;</span></a></li>
                  {% endif %}
                </ul>
              {% endif %}    
            </div>
        </div>
    </section>
    <!-- /.content -->
  </div>
{% endblock content %}

{% block javascript %}

{% endblock javascript %}