aws/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import *
from django.conf.urls.static import static #For img 
from django.conf import settings #For img
# For password reset email template to render html tags
from django.contrib.auth import views as auth_views

# handler404 = 'main.views.error_404_view'
from dashreporting.views import *
from django.urls import re_path

urlpatterns = [
    # For password reset email template to render html tags
    # path('accounts/password_reset/', auth_views.PasswordResetView.as_view(
    #     html_email_template_name='registration/password_reset_email.html'
    # )),

    path('accounts/', include('django.contrib.auth.urls')),

    path('admin/', admin.site.urls),

    path('', include('main.urls')),

    path('todo/', include('todo.urls')),
    path('quiz/', include('quiz.urls')),
    path('blog/', include('blog.urls')),
    path('shop/', include('shop.urls')),

    path('dash/', include('dashreporting.urls')),
    path('calendar/', include('calendar_app.urls')),

    path('login/', user_login, name="login"),
    path('logout/', user_logout, name="logout"),
    path('signup/', signup, name="signup"),
    # path('signup-done/', signup_done, name="signup_done"),
    path('change-password/', change_password, name="change-password"),

    path('ckeditor/', include('ckeditor_uploader.urls')), #for ckeditor

    # Django Dash Plotly 
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
    

] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT) #For img

shop/urls.py
from django.urls import path
from shop.views import *

# Define app name to call
app_name = "shop"

urlpatterns = [
    path('products/', products, name="products"),
    path('product/<slug:slug>/', product, name='product'),

    path('product-list/', product_list, name="product_list"),
    path('product-create/', product_create, name="product_create"),    
    path('product/<slug:slug>/update/', product_update, name='product_update'),
    path('product/<int:id>/delete/', product_delete, name='product_delete'),

    path('gallery/<int:id>/delete/', gallery_delete, name='gallery_delete'),
    path('gallery-create/', gallery_create, name='gallery_create'),

    path('category-list/', category_list, name="category_list"),
    path('category/<int:id>/delete/', category_delete, name='category_delete'),
    path('category/<int:id>/update/', category_update, name='category_update'),

    path('shopcart/', shop_cart_list, name='shopcart'),
    path('add-to-cart/<int:id>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<int:id>/', remove_from_cart, name='remove_from_cart'),

    path('checkout/', checkout, name='checkout'),
]

shop/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.db.models.signals import pre_save
from django_countries.fields import CountryField

class Category(models.Model):
    title = models.CharField(max_length=250)
    parent = models.ForeignKey("Category", on_delete = models.SET_NULL, null=True, blank = True, related_name='children')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
            return self.title

LABEL_CHOICES = (
    ('new', 'new'),
    ('free_shipping', 'free_shipping')
)

class Product(models.Model):
    title = models.CharField(max_length = 100)
    code = models.CharField(max_length = 100)
    short_description = models.TextField(null=True, blank=True)
    description = models.TextField()    
    image = models.ImageField(upload_to='pictures/%Y/%m/%d/' , max_length=255, null=True, blank=True)
    price = models.FloatField()
    discount_price = models.FloatField(blank = True, null = True )
    category = models.ForeignKey(Category, on_delete = models.CASCADE, null=True, blank=True)
    label = models.CharField(choices = LABEL_CHOICES, max_length=20)
    stock = models.IntegerField(default=1, null=True, blank=True)
    slug = models.SlugField(unique = True, editable = False, max_length = 250)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now= True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("shop:product", kwargs={'slug':self.slug})

    def get_add_to_cart_url(self):
        return reverse("shop:add-to-cart", kwargs={'slug':self.slug})

    def get_remove_from_cart_url(self):
        return reverse("shop:remove-from-cart", kwargs={'slug':self.slug})

class Order(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE, blank = True, null = True)
    first_name = models.CharField(max_length = 50)
    last_name= models.CharField(max_length = 50)
    company = models.CharField(max_length = 150, blank = True, null = True)
    address = models.CharField(max_length = 150)
    city = models.CharField(max_length = 70, blank = True, null = True)
    country = CountryField(blank_label='(select country)')
    phone = models.CharField(max_length = 50)
    total = models.FloatField()
    ordered = models.BooleanField(default = False)
    note = models.TextField(null = True, default="")
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.user.email

class OrderDetail(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, blank = True, null = True)
    quantity = models.IntegerField(default=1)
    price = models.FloatField()
    total = models.FloatField()
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now= True)

class ShopCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default = 1)

    def __str__(self):
        return self.product

    @property
    def amount(self):
        return (self.quantity*self.product.price)

class ProductGallery(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='pictures/%Y/%m/%d/' , max_length=255)

    def __str__(self):
        return self.product.title

# Create unique slug .
def create_slug(instance, new_slug = None):
    slug = slugify(instance.title)     
    if new_slug is not None: 
        slug = new_slug 
    else: 
        slug = slugify(instance.title)

    qs = Product.objects.filter(slug = slug).order_by("-id")
    exists = qs.exists()
    if exists: 
        new_slug = "{slug}-{id}".format( slug = slug, id = qs.first().id)               
        return create_slug(instance, new_slug = new_slug) 
    return slug 

def pre_save_receiver(sender, instance, *args, **kwargs): 
   if not instance.slug: 
       instance.slug = create_slug(instance) 
    
pre_save.connect(pre_save_receiver, sender = Product) 

shop/views.py
from django.shortcuts import render, get_object_or_404
from shop.models import Product, Category, ShopCart, ProductGallery
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from forms.shop_category import ShopCategoryForm
from forms.shop_product import ShopProductForm
from forms.shop_checkout import ShopCheckoutForm
from django.contrib.auth.decorators import login_required
from aws.role_decorator import role_required

def products(request):
    context = {}
    product_list = Product.objects.all()
    context['products'] = product_list
    return render(request, 'shop/products.html', context)

def product(request, slug):
    context = {}
    product = Product.objects.filter(slug__iexact = slug).first()
    galleries = ProductGallery.objects.filter(product = product)
    context['product'] = product
    context['galleries'] = galleries
    return render(request, 'shop/product.html', context)

@login_required(login_url = "/login/")
def product_list(request):
    context = {}    
    categories = Category.objects.prefetch_related("parent__children").all()
    product_list = Product.objects.all()
    context['products'] = product_list
    context['categories'] = categories   
    return render(request, 'shop/product_list.html', context)

@login_required(login_url = "/login/")
@role_required(allowed_roles = ["admin"])
def product_create(request):
    context = {}
    if request.method == "POST":
        try:
            form = ShopProductForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                messages.success(request, "Your product has been successfully submitted.")
                return HttpResponseRedirect(reverse('shop:product_list'))
        except Exception:
            messages.warning(request, "There was a problem.")
            return render(request, 'shop/post_create.html', context)
    else:
        form = ShopProductForm()    
    context['form'] = form
    return render(request, 'shop/product_create.html', context)

@login_required(login_url = "/login/")
@role_required(allowed_roles = ["admin"])
def product_update(request, slug):
    context = {}
    user = request.user
    product = Product.objects.filter(slug = slug).first()
    galleries = ProductGallery.objects.filter(product = product)
    if request.method == "POST":
        try:
            form = ShopProductForm(request.POST, request.FILES, instance=product)
            if form.is_valid():
                form.save()
                messages.success(request, "Your product has been successfully updated.")
                return HttpResponseRedirect(reverse('shop:product_list'))
        except Exception:
            messages.warning(request, "There was a problem.")
            return render(request, 'shop/product_edit.html', context)
    else:
        form = ShopProductForm(instance = product)    
    context['form'] = form
    context['product'] = product
    context['galleries'] = galleries
    return render(request, 'shop/product_edit.html', context)

@login_required(login_url = "/login/")
@role_required(allowed_roles = ["admin"])
def product_delete(request, id):
    if request.method == "POST":
        id = id
        Product.objects.filter(id = id).delete()
        messages.success(request, "Successfully deleted ")
    return HttpResponseRedirect(reverse('shop:product_list'))

@login_required(login_url = "/login/")
@role_required(allowed_roles = ["admin"])
def gallery_create(request):
    url = request.META.get('HTTP_REFERER')
    if request.method == "POST":
        product_id = request.POST['product_id']
        gallery_image = request.FILES['gallery_image']
        product = Product.objects.filter(id = product_id).first()
        data = ProductGallery(product = product, )
        data.product = product
        data.image = gallery_image
        data.save()
        messages.success(request, "Successfully added ")
    return HttpResponseRedirect(url)

@login_required(login_url = "/login/")
@role_required(allowed_roles = ["admin"])
def gallery_delete(request, id):
    url = request.META.get('HTTP_REFERER')
    if request.method == "POST":
        id = id
        ProductGallery.objects.filter(id = id).delete()
        messages.success(request, "Successfully deleted ")
        return HttpResponseRedirect(url)
    return HttpResponseRedirect(url)

@login_required(login_url = "/login/")
@role_required(allowed_roles = ["admin"])
def category_list(request):
    context = {}
    categories = Category.objects.prefetch_related("parent__children").all()
    context['categories'] = categories
    #Create Category
    if request.method == "POST":
        try:
            form = ShopCategoryForm(request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, "Your category has been successfully submitted.")
                return HttpResponseRedirect(reverse('shop:category_list'))
        except Exception:
            messages.warning(request, "There was a problem.")
            return HttpResponseRedirect(reverse('shop:category_list'))
    else:
        form = ShopCategoryForm()    
    context['form'] = form
    return render(request, 'shop/category_list.html', context)

@login_required(login_url = "/login/")
@role_required(allowed_roles = ["admin"])
def category_delete(request, id):
    if request.method == "POST":
        id = id
        Category.objects.filter(id = id).delete()
        messages.success(request, "Successfully deleted ")
    return HttpResponseRedirect(reverse('shop:category_list'))

@login_required(login_url = "/login/")
@role_required(allowed_roles = ["admin"])
def category_update(request, id):
    context = {}    
    if request.method == "POST":
        parent = request.POST["parent"]
        title = request.POST["title"]
        try:
            if parent != "None":
                parent = Category.objects.filter(title = parent).first()
            else:
                parent =""
            category = Category.objects.filter(id = id).first()            
            category.parent = parent
            category.title = title
            category.save()
            messages.success(request, "Edited Successfully ")
            return HttpResponseRedirect(reverse('shop:category_list'))
        except Exception as e:
            print(e)
            messages.warning(request, "There was a problem while saving. ")
            return HttpResponseRedirect(reverse('shop:category_list'))
    return HttpResponseRedirect(reverse('shop:category_list'))

def shop_cart_list(request):
    current_user = request.user
    cart_products = ShopCart.objects.filter(user_id = current_user.id)
    cart_total = 0
    for rs in cart_products:
        if rs.product.discount_price:
            cart_total += rs.quantity*rs.product.discount_price
        else:
            cart_total += rs.quantity*rs.product.price        
    context = {}
    context['cart_total'] = cart_total
    context['cart_products'] = cart_products
    return render(request, 'shop/shop_cart.html', context)

@login_required(login_url = "/login/")
def add_to_cart(request, id = None):
    url = request.META.get('HTTP_REFERER') # Get previous url.
    if request.method == "POST":
        current_user = request.user
        try:
            q1 = ShopCart.objects.get(user_id = current_user.id, product_id = id)
        except ShopCart.DoesNotExist:
            q1 = None

        if q1 != None: #Update quantity to exist product quantity
            messages.success(request, "Product already added to cart ")
            return HttpResponseRedirect(url)
        else: #Add new item to shop cart
            data = ShopCart(user_id = current_user.id, product_id = id, quantity = 1 ) 
            data.save()
            messages.success(request, "Product added to cart ")
            return HttpResponseRedirect(url)
    return HttpResponseRedirect(reverse('shop:products'))

@login_required(login_url = "/login/")
def remove_from_cart(request, id = None):
    product = get_object_or_404(Product, id = id)
    shop_cart_qs = ShopCart.objects.filter(user = request.user, product = product)
    if shop_cart_qs.exists():
        cart_product = shop_cart_qs[0]
        cart_product.delete()
        messages.success(request, "This product was removed from your cart.")
    else:
        messages.info(request, "This product was not in your cart.")
        return HttpResponseRedirect(reverse("shop:shopcart"))            
    return HttpResponseRedirect(reverse("shop:shopcart"))  

def checkout(request):
    current_user = request.user
    cart_products = ShopCart.objects.filter(user_id = current_user.id)
    cart_total = 0
    for rs in cart_products:
        if rs.product.discount_price:
            cart_total += rs.quantity*rs.product.discount_price
        else:
            cart_total += rs.quantity*rs.product.price
        
    if request.method == "POST":
        #Send Credit card information to bank and get and result
        #If payment true sell course  
        data = Order()
        data.first_name = request.POST['first_name']
        data.last_name = request.POST['last_name']
        data.company = request.POST['company']
        data.address = request.POST['address']
        data.country = request.POST['country']
        data.phone= request.POST['phone']
        data.total = cart_total
        data.save()

        for rs in cart_products:
            detail = OrderDetail()
            detail.order_id = data.id
            detail.product_id = rs.product_id
            detail.user_id = current_user.id
            detail.quantity = rs.quantity
            detail.price = rs.product.price
            detail.total = rs.amount
            detail.save()
        ShopCart.objects.filter(user_id = current_user.id).delete() #Empty cart
        messages.success(request, "Order completed. Thank you.")

templates/shop/category_list.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %} <!-- Crispy Forms --> 
{% block css %}

{% endblock css %}

{% block content %}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Categories</h1>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
     <!-- Main content -->
     <section class="content">
      <div class="row">
        <div class="col-12">     
          <!-- /.card -->
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">Category List</h3>
              <div class="card-tools">
                <button type="button" class="btn btn-info float-right" data-toggle="modal" data-target="#modal-default"><i class="fas fa-plus"></i> Add New Category</button>
              </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <table id="example1" class="table table-striped">
                <thead>
                    <tr>
                      <th>Category</th>
                      <th>Subcategory</th>
                      <th></th>
                    </tr>
                    </thead>
                <tbody>
                {% for category in categories %}
                {% if category.parent %}
                <tr>
                  <td>{{category.parent}}</td>
                  <td>{{category.title}}</td>                                                   
                <td class="project-actions text-right">
                    <button class="btn btn-info btn-sm" data-toggle="modal" data-target="#modal-default-edit-{{category.id}}">
                        <i class="fas fa-pencil-alt">
                        </i>
                        Edit
                    </button>
                    <button class="btn btn-danger btn-sm" data-toggle="modal" data-target="#modal-default-delete-{{category.id}}">
                        <i class="fas fa-trash">
                        </i>
                        Delete
                    </button>
                    <!-- /. Delete modal -->
                    <form action="{%  url 'shop:category_update' category.id %}" method="POST">
                        {% csrf_token %}
                    <div class="modal fade" id="modal-default-edit-{{category.id}}">
                        <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title">Edit Category</h4>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                  <span aria-hidden="true">&times;</span>
                                </button>
                              </div>                  
                              <div class="modal-body">
                                <div class="form-group ">
                                  {% csrf_token %}
                                  <div class="form-group">
                                    <label for="inputStatus" class="float-left">Parent</label>
                                    <select class="form-control-sm custom-select" name="parent">
                                        <option selected value="{{category.parent}}">{{category.parent}}</option>                                     
                                        {% for category in categories %}
                                            {% if category.parent is None %}
                                            <option value="{{category.id}}">{{category.title}}</option>
                                            {% endif %}
                                        {% endfor %}
                                    </select>
                                   </div>
                                   <div class="form-group">
                                    <label for="title-category" class="float-left">*Title</label>
                                    <input type="text" id="title-category" class="form-control" name="title" value="{{category.title}}">
                                </div>
                                </div>
                              </div>
                              <div class="modal-footer justify-content-between">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-primary">Save</button>
                              </div>
                        </div>
                        <!-- /.modal-content -->
                        </div>
                        <!-- /.modal-dialog -->
                    </div>
                    </form>
                     <!-- /. Delete modal -->
                    <form action="{%  url 'shop:category_delete' category.id %}" method="POST">
                        {% csrf_token %}
                    <div class="modal fade" id="modal-default-delete-{{category.id}}">
                        <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header" style="border-bottom:none;">                    
                            <i class="fas fa-exclamation-circle fa-5x" style="margin:0 auto; color:#F8BB86;"></i>
                            </div>
                            <div class="modal-body text-muted" style="margin:0 auto;border-bottom:none;">
                                <h3 >Are you sure to Delete?</h3>
                            </div>
                            <div class="modal-footer justify-content-between">
                            <button type="button" class="btn btn-default" data-dismiss="modal">No, thanks</button>
                            <button type="submit" class="btn btn-primary">Yes, Delete it</button>
                            </div>
                        </div>
                        <!-- /.modal-content -->
                        </div>
                        <!-- /.modal-dialog -->
                    </div>
                    </form>
                </td>
                {% endif %}
                {% endfor %}
                </tr>                
                </tbody>
                <tfoot>
                <tr>
                    <th>Category</th>
                    <th>Subcategory</th>
                    <th></th>
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
      <!-- /.modal -->
      <form action="" method="POST">
        {% csrf_token %}
        <div class="modal fade" id="modal-default">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h4 class="modal-title">Add Category</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <div class="form-group">
                  {% csrf_token %}
                  {{form | crispy}}
                </div>
              </div>
              <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Save</button>
              </div>
            </div>
            <!-- /.modal-content -->
          </div>
          <!-- /.modal-dialog -->
        </div>
      </form>
      <!-- /.modal -->
    </section>
    <!-- /.content -->
  </div>
{% endblock content %}

{% block javascript %}
<!-- DataTables -->
<script src="{% static 'assets/plugins/datatables/jquery.dataTables.js' %} "></script>
<script src="{% static 'assets/plugins/datatables-bs4/js/dataTables.bootstrap4.js' %} "></script>
<!-- page script -->
<script>
  $(function () {
    $("#example1").DataTable();
  });
</script>
{% endblock javascript %}

templates/shop/product_list.html
{% extends 'base.html' %}
{% load static %}
{% block css %}

{% endblock css %}

{% block content %}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Products</h1>
          </div>
          <div class="col-sm-6">
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-12">      
          <!-- /.card -->
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">Product List</h3>
              <div class="card-tools">
                <a href="{%  url 'shop:product_create' %}" class="btn btn-info float-right" ><i class="fas fa-plus"></i> Add Product</a>
              </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <table id="example1" class="table table-striped">
                <thead>
                <tr>
                  <th>Image</th>
                  <th>Product Name</th>
                  <th>Price</th>
                  <th>Category</th>
                  <th></th>
                </tr>
                </thead>
                <tbody>
                {% for product in products %}
                <tr>
                  <td>
                    {% if product.image %}
                      <img src="{{product.image.url}}" width="30px" class="img-size-50 mr-1" alt="User-Profile-Image"> 
                    {% else %}
                      <img src="{% static 'assets/dist/img/user2-160x160.jpg' %}" width="30px" class="img-size-30 img-circle mr-1" alt="User-Profile-Image">
                    {% endif %}  
                  </td>
                  <td>{{product.title}}</td>
                  <td>                    
                    {% if product.discount_price %}
                      ${{product.discount_price | floatformat:2}} <del>${{product.price | floatformat:2}}</del>                                                                       
                    {% else %}
                      ${{product.price | floatformat:2}}
                    {% endif %}
                  </td>
                  <td>{{product.category.title}}</td>
                </td>
                <td class="project-actions text-right">
                    <a class="btn btn-primary btn-sm" href="{{product.get_absolute_url}}">
                        <i class="fas fa-folder">
                        </i>
                        View
                    </a>
                    <a class="btn btn-info btn-sm" href="{%  url 'shop:product_update' product.slug %}">
                        <i class="fas fa-pencil-alt">
                        </i>
                        Edit
                    </a>
                    <button class="btn btn-danger btn-sm" data-toggle="modal" data-target="#modal-default-delete-{{product.id}}">
                      <i class="fas fa-trash">
                      </i>
                      Delete
                  </button>
                  <!-- /. Delete modal -->
                  <form action="{%  url 'shop:product_delete' product.id %}" method="POST">
                    {% csrf_token %}
                  <div class="modal fade" id="modal-default-delete-{{product.id}}">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header" style="border-bottom:none;">                    
                          <i class="fas fa-exclamation-circle fa-5x" style="margin:0 auto; color:#F8BB86;"></i>
                        </div>
                        <div class="modal-body text-muted" style="margin:0 auto;border-bottom:none;">
                            <h3 >Are you sure to Delete?</h3>
                        </div>
                        <div class="modal-footer justify-content-between">
                          <button type="button" class="btn btn-default" data-dismiss="modal">No, thanks</button>
                          <button type="submit" class="btn btn-primary">Yes, Delete it</button>
                        </div>
                      </div>
                      <!-- /.modal-content -->
                    </div>
                    <!-- /.modal-dialog -->
                  </div>
                  </form>
                </td>
                </tr>
                {% endfor %}
                </tbody>
                <tfoot>
                <tr>
                  <th>Image</th>
                  <th>Product Name</th>
                  <th>Price</th>
                  <th>Category</th>
                  <th></th>
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
{% endblock content %}

{% block javascript %}

{% endblock javascript %}