aws/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import *
from django.conf.urls.static import static #For img 
from django.conf import settings #For img
# For password reset email template to render html tags
from django.contrib.auth import views as auth_views

# handler404 = 'main.views.error_404_view'
from dashreporting.views import *
from django.urls import re_path

urlpatterns = [
    # For password reset email template to render html tags
    # path('accounts/password_reset/', auth_views.PasswordResetView.as_view(
    #     html_email_template_name='registration/password_reset_email.html'
    # )),

    path('accounts/', include('django.contrib.auth.urls')),

    path('admin/', admin.site.urls),

    path('', include('main.urls')),

    path('todo/', include('todo.urls')),
    path('quiz/', include('quiz.urls')),
    path('blog/', include('blog.urls')),
    path('shop/', include('shop.urls')),

    path('dash/', include('dashreporting.urls')),
    path('calendar/', include('calendar_app.urls')),

    path('login/', user_login, name="login"),
    path('logout/', user_logout, name="logout"),
    path('signup/', signup, name="signup"),
    # path('signup-done/', signup_done, name="signup_done"),
    path('change-password/', change_password, name="change-password"),

    path('ckeditor/', include('ckeditor_uploader.urls')), #for ckeditor

    # Django Dash Plotly 
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
    

] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT) #For img

quiz/urls.py
from django.urls import path
from quiz.views import *

# Define app name to call
app_name = "quiz"

urlpatterns = [
    path('subject-list/', subject_list, name="subject_list"),
    path('subject/<int:id>/update/', subject_update, name='subject_update'),
    path('subject/<int:id>/delete/', subject_delete, name='subject_delete'),
    path('subject-create/', subject_create, name="subject_create"),

    path('topic/<int:id>/update/', topic_update, name='topic_update'),
    path('topic/<int:id>/delete/', topic_delete, name='topic_delete'),
    path('topic-create/', topic_create, name="topic_create"),

    path('question-list/', question_list, name="question_list"),
    
    path('question-create/', question_create, name="question_create"),
    path('question/<int:id>/update/', question_update, name='question_update'),
    path('question/<int:id>/delete/', question_delete, name='question_delete'),
    path('question/', question, name="question"),

    path('quiz-list/', quiz_list, name="quiz_list"),
    path('quiz/<int:id>/', quiz, name="quiz"),
    path('quiz/<int:id>/update/', quiz_update, name='quiz_update'),
    path('quiz/<int:id>/delete/', quiz_delete, name='quiz_delete'),
    path('quiz-create/', quiz_create, name="quiz_create"),

    path('add-to-quiz/<int:id>/', add_to_quiz, name="add_to_quiz"),

    path('my-quizzes/', my_quizzes, name="my_quizzes"),
    path('my-quiz/<int:id>/', my_quiz, name="my_quiz"),     
    #=============== QUIZs AJAX REQUEST =====================
    path('quiz_test_action/', quiz_test_action, name="quiz_test_action"),
    path('get-topics-ajax/', get_topics_ajax, name="get_topics_ajax"),

    path('quizzes/', quizzes, name="quizzes"),
    path('quiz-start/<int:id>/', quiz_start, name="quiz_start"),
    path('quiz-test/<int:id>/', quiz_test, name="quiz_test"),
    path('quiz-result/<int:id>/', quiz_result, name="quiz_result"),
]

quiz/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField #CKEditor

class Subject(models.Model):
    title = models.CharField(max_length = 250, null = True, blank = True)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    def __str__(self):
        return "{0}".format(self.title)

class Topic(models.Model):
    title = models.CharField(max_length = 250, null = True, blank = True)
    subject = models.ForeignKey(Subject, on_delete = models.CASCADE, related_name = "topics" )
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    def __str__(self):
        return "{0}".format(self.title)

LEVEL_CHOICES = (
    ('L', 'LOW'),
    ('M', 'MEDIUM'),
    ('A', 'ADVANCED'),
)

ANSWER_CHOICES = (
    ('A', 'A'),
    ('B', 'B'),
    ('C', 'C'),
    ('D', 'D'),
)
class Quiz(models.Model):
    user = models.ForeignKey(User, on_delete= models.CASCADE, null = True, blank = True)   
    quiz_title = models.CharField(max_length = 150, null = True, blank = True)
    quiz_note = models.CharField(max_length = 500, null = True, blank = True)
    quiz_datetime = models.DateTimeField(null = True, blank = True)
    quiz_duration = models.PositiveSmallIntegerField(null=True, blank = True)
    marks_per_right_answer = models.DecimalField( max_digits=4, decimal_places=2, null = True, blank = True)
    marks_per_wrong_answer = models.DecimalField( max_digits=4, decimal_places=2, null = True, blank = True)
    quiz_status = models.BooleanField(default= False, blank = True)
    quiz_code = models.CharField(max_length = 50, null = True, blank = True)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now= True)

    def __str__(self):
        return "{0}".format(self.quiz_title)

class Question(models.Model):
    title = RichTextUploadingField(null = True, blank = True)
    quiz = models.ManyToManyField(Quiz, blank =True)
    image = models.ImageField(upload_to = 'pictures/%Y/%m/%d/', max_length = 255, null=True, blank =True)
    topic = models.ForeignKey(Topic, on_delete = models.CASCADE )
    level = models.CharField(choices = LEVEL_CHOICES, default = 'L', max_length=2)  
    option_a = models.CharField(max_length = 1000, null = True, blank = True)
    option_b = models.CharField(max_length = 1000, null = True, blank = True)
    option_c = models.CharField(max_length = 1000, null = True, blank = True)
    option_d = models.CharField(max_length = 1000, null = True, blank = True)
    answer = models.CharField(choices = ANSWER_CHOICES, max_length=2, null = True, blank = True)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    def __str__(self):
        return "{0}".format(self.title)

    
class StudentExam(models.Model):
    user = models.ForeignKey(User, on_delete= models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete= models.CASCADE)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

RESULT_CHOICES = (
    ('CORRECT', 'CORRECT'),
    ('WRONG', 'WRONG'),
    ('EMPTY', 'EMPTY'),
)

class StudentAnswers(models.Model):
    studentexam = models.ForeignKey(StudentExam, on_delete= models.CASCADE)    
    question = models.ForeignKey(Question, on_delete= models.CASCADE)
    answer = models.CharField(choices = ANSWER_CHOICES, max_length=2)
    marks = models.DecimalField( max_digits=4, decimal_places=2, null = True, blank = True)
    result = models.CharField(choices = RESULT_CHOICES, max_length=10, default = "EMPTY")

# class StudentAssesments(models.Model):

quiz/views.py
from django.shortcuts import render
from quiz.models import Question, Topic, Subject, Quiz, StudentExam, StudentAnswers
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.urls import reverse
from django.contrib import messages
from forms.quiz_subject import QuizSubjectForm
from forms.quiz_topic import QuizTopicForm
from forms.quiz_quiz import QuizQuizForm
from forms.quiz_question import QuizQuestionForm
from django.contrib.auth.decorators import login_required
from aws.role_decorator import role_required
from django.db.models import Avg, Count, Min, Sum

@login_required(login_url = "/login/")
@role_required(allowed_roles = ["admin", "visitor"])
def my_quizzes(request):
    context = {}
    current_user = request.user
    quizzes = StudentExam.objects.filter(user = current_user)
    context['my_quizzes'] = quizzes
    return render(request, 'quiz/my_quizzes.html', context)

@login_required(login_url = "/login/")
@role_required(allowed_roles = ["admin", "visitor"])
def my_quiz(request, id=None):
    context = {}
    total_point = ""
    student_exam = StudentExam.objects.filter(id = id).first()
    total_question = Question.objects.filter(quiz = student_exam.quiz).count()
    correct_answer = StudentAnswers.objects.filter(studentexam = student_exam, result = "CORRECT").count()
    wrong_answer = StudentAnswers.objects.filter(studentexam = student_exam, result = "WRONG").count()
    correct_point = StudentAnswers.objects.filter(studentexam = student_exam, result = "CORRECT").aggregate(Sum('marks'))
    wrong_point = StudentAnswers.objects.filter(studentexam = student_exam, result = "CORRECT").aggregate(Sum('marks'))
    if correct_point['marks__sum']:
        total_point = correct_point['marks__sum'] - wrong_point['marks__sum']
    context['student_exam'] = student_exam
    context['total_question'] = total_question
    context['correct_answer'] = correct_answer
    context['wrong_answer'] = wrong_answer
    context['marks_per_right_answer'] = student_exam.quiz.marks_per_right_answer
    context['marks_per_wrong_answer'] = student_exam.quiz.marks_per_wrong_answer
    if total_point != "":
        context['total_point'] = total_point
    quiz_questions =  StudentAnswers.objects.filter(studentexam = student_exam)
    context['quiz_questions'] = quiz_questions
    return render(request, 'quiz/my_quiz.html', context)

def quizzes(request):
    context = {}
    quizs = Quiz.objects.all()
    context['quizs'] = quizs
    return render(request, 'quiz/quizzes.html', context)

@login_required(login_url = "/login/")
@role_required(allowed_roles = ["admin", "visitor"])
def quiz_start(request, id=None):
    context = {}
    quiz = Quiz.objects.filter(id = id).first()
    total_question = Question.objects.filter(quiz = quiz).count()
    context['quiz'] = quiz
    context['total_question'] = total_question
    return render(request, 'quiz/quiz_start.html', context)

@login_required(login_url = "/login/")
@role_required(allowed_roles = ["admin", "visitor"])
def quiz_test(request, id=None):
    context = {}
    current_user = request.user
    quiz = Quiz.objects.filter(id = id).first()
    question_1 = Question.objects.filter(quiz = quiz).first()
    next_question = Question.objects.filter(quiz = quiz, pk__gt = question_1.id).first() 
    try:
        student_exam = StudentExam()
        student_exam.user = current_user
        student_exam.quiz = quiz
        student_exam.save()
    except Exception:
        pass
    context['quiz'] = quiz
    context['question_1'] = question_1
    context['next_question'] = next_question
    context['student_exam'] = student_exam   
    return render(request, 'quiz/quiz_test.html', context)

#=============== AJAX REQUESTS =====================
@login_required(login_url = "/login/") 
@role_required(allowed_roles = ["admin", "visitor"])
def quiz_test_action(request):
    checked_answer = ""    
    if request.method == "POST":        
        question_id = request.POST['question_id']
        next_question_id = request.POST['next_question_id']
        student_exam_id = request.POST['student_exam']
        answer = request.POST['answer']
        next_previous = request.POST['next_previous']

        solved_question = Question.objects.filter(id = question_id).first() # SOLVED QUESTION
        quiz = Quiz.objects.filter(question = solved_question).first()
        #SAVE OR UPDATED ANSWER   try_catch  block must be
        student_exam = StudentExam.objects.filter(id = student_exam_id).first()
        #### Student Question Answer and Check answer If it is correct or wrong #######
        result = ""
        marks = 0
        if answer == "empty":
            answer = ""
            result = ""
            marks = 0
        student_answer = StudentAnswers.objects.filter(studentexam = student_exam, question = solved_question).first()
        if student_answer:
            student_answer.answer = answer            
            if answer == solved_question.answer:
                result = "CORRECT"
                marks = quiz.marks_per_right_answer
            elif answer != "":
                result = "WRONG"
                marks = quiz.marks_per_wrong_answer
            student_answer.result = result
            student_answer.marks = marks
            student_answer.save()
        else:
            if answer == solved_question.answer:
                result = "CORRECT"
                marks = quiz.marks_per_right_answer
            elif answer != "":
                result = "WRONG"
                marks = quiz.marks_per_wrong_answer
            student_answer = StudentAnswers.objects.create(studentexam = student_exam, question = solved_question, answer = answer,
                                marks = marks, result = result)
        #### Student Question Answer and Check answer If it is correct or wrong END! #######
        if next_previous == "next":
            question = Question.objects.filter(id = next_question_id).first() 
            nq = StudentAnswers.objects.filter(studentexam = student_exam, question = question).first()
            if nq:
                checked_answer = nq.answer

        if next_previous == "previous":
            previous_question = Question.objects.filter(quiz = quiz, pk__lt = question_id).last()# PROBLEM
            question = previous_question# solved_question
            pq = StudentAnswers.objects.filter(studentexam = student_exam, question = question).first()
            if previous_question:
                checked_answer = pq.answer

        previous_question = Question.objects.filter(quiz = quiz, pk__lt = question.id).last()
        next_question = Question.objects.filter(quiz = quiz, pk__gt = question.id).first()        
        ##########################################################################################
        disabled = ""
        a, b, c, d = "", "", "", ""
        if checked_answer == "A":
            a = "checked"
        elif checked_answer == "B":
            b = "checked"
        elif checked_answer == "C":
            c = "checked"
        elif checked_answer == "D":
            d = "checked"
        else:
            a, b, c, d = "", "", "", ""
        # Check whether there is  an image
        image = ""
        if question.image:
            image = '<div class="container"><img src="{image_url}" class="mb-2" style="width:100%; max-width:800px; height: auto;" alt="Question-Image">\
                </div>'.format(image_url = question.image.url )
        # Check whether there is  an image 

        load_question = '<div id="load_question">\
        <div class="card-body">{image}\
            <p><strong><span id="quizQuestion">1</span></strong> {question_title}</p>\
            <div class="form-group clearfix">\
                <div class="row"><div class="icheck-primary d-inline">\
                        <input type="radio" id="radioPrimary1" name="answer" {a} value="A">\
                        <label for="radioPrimary1"> <strong>A ) </strong>{question_option_a}</label> </div></div>\
                <div class="row"><div class="icheck-primary d-inline">\
                    <input type="radio" id="radioPrimary2" name="answer" {b} value="B">\
                    <label for="radioPrimary2"> <strong>B ) </strong>{question_option_b}</label></div></div>\
                <div class="row"><div class="icheck-primary d-inline">\
                        <input type="radio" id="radioPrimary3" name="answer" {c} value="C">\
                        <label for="radioPrimary3"><strong>C ) </strong> {question_option_c}</label></div></div>\
                <div class="row"><div class="icheck-primary d-inline">\
                        <input type="radio" id="radioPrimary4" name="answer" {d} value="D">\
                        <label for="radioPrimary4"><strong>D ) </strong> {question_option_d}</label></div></div></div>\
            '.format(question_title = question.title, question_option_a = question.option_a, question_option_b = question.option_b,
                        question_option_c = question.option_c, question_option_d = question.option_d,
                        a = a, b  = b, c = c, d = d, image = image )

        if next_question and next_previous == "next":
            load_question += '<button type="button" class="btn btn-info btn-flat {disabled}" onclick="PreviousQuestion();">&laquo; Previous</button>\
            <button type="button" class="btn btn-info btn-flat {disabled}" onclick="NextQuestion();">Next &raquo;</button>\
            <a href="/quiz/quiz-result/{student_exam_id}/" class="btn btn-info btn-flat float-right">Finish Quiz</a>\
            <input type="hidden" name="question_id" value="{question_id}">\
            <input type="hidden" name="student_exam" value="{student_exam_id}">\
            <input type="hidden" name="next_question_id" value="{next_question_id}"></div>'.format( 

templates/quiz/question_list.html
{% extends 'base.html' %}
{% load static %}
{% block css %}

{% endblock css %}

{% block content %}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Questions</h1>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
     <!-- Main content -->
     <section class="content">
      <div class="row">
        <div class="col-12">      
          <!-- /.card -->
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">Question List</h3>
              <div class="card-tools">
                <a href="{%  url 'quiz:question_create' %}" class="btn btn-info float-right" ><i class="fas fa-plus"></i> Add Question</a>
              </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <table id="example1" class="table table-striped">
                <thead>
                <tr>
                  <th>Question</th>
                  <th>Topic</th>
                  <th>Subject</th>
                  <th>Level</th>
                  <th></th>
                </tr>
                </thead>
                <tbody>
                {% for question in questions %}
                <tr>
                  <td>{{question.title | safe}}</td>
                  <td>{{question.topic.title}}</td>
                  <td>{{question.topic.subject.title}}</td>
                  <td>{{question.get_level_display}}</td>
                </td>
                <td class="project-actions text-right">
                    <button class="btn btn-success btn-sm" data-toggle="modal" data-target="#modal-add_to_quiz-{{question.id}}">
                      <i class="fas fa-plus">
                      </i>
                      Add to Quiz
                    </button>
                    <a class="btn btn-info btn-sm" href="{%  url 'quiz:question_update' question.id %}">
                        <i class="fas fa-pencil-alt">
                        </i>
                        Edit
                    </a>
                    <button class="btn btn-danger btn-sm" data-toggle="modal" data-target="#modal-question-delete-{{question.id}}">
                      <i class="fas fa-trash">
                      </i>
                      Delete
                    </button>
                    <!-- /. Delete modal -->
                  <form action="{%  url 'quiz:question_delete' question.id %}" method="POST">
                    {% csrf_token %}
                  <div class="modal fade" id="modal-question-delete-{{question.id}}">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header" style="border-bottom:none;">                    
                          <i class="fas fa-exclamation-circle fa-5x" style="margin:0 auto; color:#F8BB86;"></i>
                        </div>
                        <div class="modal-body text-muted" style="margin:0 auto;border-bottom:none;">
                            <h3 >Are you sure to Delete?</h3>
                        </div>
                        <div class="modal-footer justify-content-between">
                          <button type="button" class="btn btn-default" data-dismiss="modal">No, thanks</button>
                          <button type="submit" class="btn btn-primary">Yes, Delete it</button>
                        </div>
                      </div>
                      <!-- /.modal-content -->
                    </div>
                    <!-- /.modal-dialog -->
                  </div>
                  </form>
                  <!-- /. Add to quiz modal -->
                  <form action="{%  url 'quiz:add_to_quiz' question.id %}" method="POST">
                    {% csrf_token %}
                  <div class="modal fade" id="modal-add_to_quiz-{{question.id}}">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h4 class="modal-title">Add to Quiz</h4>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                        <div class="modal-body">
                          <div class="form-group">
                            <select id="question-subject" name="quiz_id" class="form-control-sm custom-select">
                                <option selected disabled>Choose a quiz</option>
                                {% for quiz in quizs%}
                                <option value="{{quiz.id}}">{{quiz.quiz_code}} - {{quiz.quiz_title}}</option>
                                {% endfor %}
                            </select>
                          </div>
                        </div>
                        <div class="modal-footer justify-content-between">
                          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                          <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                      </div>
                      <!-- /.modal-content -->
                    </div>
                    <!-- /.modal-dialog -->
                  </div>
                  </form>
                  <!-- /.modal -->
                </td>
                </tr>
                {% endfor %}
                </tbody>
                <tfoot>
                <tr>
                  <th>Question</th>
                  <th>Topic</th>
                  <th>Subject</th>
                  <th>Level</th>
                  <th></th>
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
{% endblock content %}

{% block javascript %}
<!-- DataTables -->
<script src="{% static 'assets/plugins/datatables/jquery.dataTables.js' %} "></script>
<script src="{% static 'assets/plugins/datatables-bs4/js/dataTables.bootstrap4.js' %} "></script>
<!-- page script -->
<script>
  $(function () {
    $("#example1").DataTable();
  });
</script>
{% endblock javascript %}

templates/quiz/quiz_list.html
{% extends 'base.html' %}
{% load static %}
{% block css %}

{% endblock css %}

{% block content %}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Quiz List</h1>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
     <!-- Main content -->
     <section class="content">
      <div class="row">
        <div class="col-12">      
          <!-- /.card -->
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">Quiz List</h3>
              <div class="card-tools">
                <a href="{%  url 'quiz:quiz_create' %}" class="btn btn-info float-right" ><i class="fas fa-plus"></i> Add Quiz</a>
              </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <table id="example1" class="table table-striped">
                <thead>
                <tr>
                  <th>Quiz Code</th>
                  <th>Quiz</th>
                  <th>Status</th>
                  <th>Duration</th>
                  <th>Quiz Datetime</th>
                  <th>Total question</th>
                  <th></th>
                </tr>
                </thead>
                <tbody>
              {% for quiz in quizs %}
                <tr>
                  <td>{{quiz.quiz_code}}</td>
                  <td>{{quiz.quiz_title}}</td>
                  <td></td>
                  <td>{{quiz.quiz_duration}} min.</td>
                  <td></td>
                  <td></td>
                <td class="project-actions text-right">
                    <a class="btn btn-primary btn-sm" href="{%  url 'quiz:quiz' quiz.id %}">
                        <i class="fas fa-folder">
                        </i>
                        View
                    </a>
                    <a class="btn btn-info btn-sm" href="{%  url 'quiz:quiz_update' quiz.id %}">
                        <i class="fas fa-pencil-alt">
                        </i>
                        Edit
                    </a>
                    <button class="btn btn-danger btn-sm" data-toggle="modal" data-target="#modal-quiz-delete-{{quiz.id}}">
                      <i class="fas fa-trash">
                      </i>
                      Delete
                    </button>
                    <!-- /. Delete modal -->
                    <form action="{%  url 'quiz:quiz_delete' quiz.id %}" method="POST">
                      {% csrf_token %}
                    <div class="modal fade" id="modal-quiz-delete-{{quiz.id}}">
                      <div class="modal-dialog">
                        <div class="modal-content">
                          <div class="modal-header" style="border-bottom:none;">                    
                            <i class="fas fa-exclamation-circle fa-5x" style="margin:0 auto; color:#F8BB86;"></i>
                          </div>
                          <div class="modal-body text-muted" style="margin:0 auto;border-bottom:none;">
                              <h3 >Are you sure to Delete?</h3>
                          </div>
                          <div class="modal-footer justify-content-between">
                            <button type="button" class="btn btn-default" data-dismiss="modal">No, thanks</button>
                            <button type="submit" class="btn btn-primary">Yes, Delete it</button>
                          </div>
                        </div>
                        <!-- /.modal-content -->
                      </div>
                      <!-- /.modal-dialog -->
                    </div>
                    </form>
                </td>
                </tr>
                {% endfor %}
                </tbody>
                <tfoot>
                <tr>
                  <th>Quiz Code</th>
                  <th>Quiz</th>
                  <th>Status</th>
                  <th>Duration</th>
                  <th>Quiz Datetime</th>
                  <th>Total question</th>
                  <th></th>
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
{% endblock content %}

{% block javascript %}
<!-- DataTables -->
<script src="{% static 'assets/plugins/datatables/jquery.dataTables.js' %} "></script>
<script src="{% static 'assets/plugins/datatables-bs4/js/dataTables.bootstrap4.js' %} "></script>
<!-- page script -->
<script>
  $(function () {
    $("#example1").DataTable();
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
    });
  });
</script>
{% endblock javascript %}

templates/quiz/quiz_result.html
{% extends 'base.html' %}
{% load static %}
{% block css %}

{% endblock css %}

{% block content %}
<div class="content-wrapper">
  <div class="container">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">

        </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">      
      <div class="page-body">
        <!-- Product list start -->
        <div class="row justify-content-md-center">
            <div class="col-md-6">
                <div class="card">
                  <div class="card-header">
                    <h3 class="card-title">QUIZ RESULTS</h3>
                  </div>
                  <!-- /.card-header -->
                  <div class="card-body">
                      QUIZ : <strong> {{student_exam.quiz.quiz_title}} </strong> 
                    <table class="table table-bordered mt-2">
                      <tbody>
                        <tr>
                            <td><strong>Quiz Code :</strong></td>
                            <td>
                              {{student_exam.quiz.quiz_code}}
                            </td>
                        </tr> 
                        <tr>
                            <td><strong>Total Question:</strong></td>
                            <td>
                                {{total_question}}
                            </td>
                        </tr> 
                        <tr>
                          <td><strong>Correct Answer :</strong></td>
                          <td>
                            {{correct_answer}}
                          </td>
                        </tr>
                        <tr>
                            <td><strong>Wrong Answer :</strong></td>
                          <td>
                            {{wrong_answer}}
                          </td>
                        </tr>
                        <tr>
                            <td><strong>Total Point :</strong></td>
                          <td>
                            {{total_point}}
                          </td>
                        </tr>
                      </tbody>
                    </table>
                    <a href="{%  url 'quiz:my_quizzes' %}" class="btn btn-primary btn-block mt-2">
                        GO TO MY QUIZ RESULTS
                    </a>
                  </div>
                  <!-- /.card-body -->
                </div>
                <!-- /.card -->

              </div>
        </div>
        <!-- Product list end -->    
      </div>
    </section>
    </div>
    <!-- /.content -->
  </div>
{% endblock content %}

{% block javascript %}

{% endblock javascript %}