aws/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import *
from django.conf.urls.static import static #For img 
from django.conf import settings #For img
# For password reset email template to render html tags
from django.contrib.auth import views as auth_views

# handler404 = 'main.views.error_404_view'
from dashreporting.views import *
from django.urls import re_path

urlpatterns = [
    # For password reset email template to render html tags
    # path('accounts/password_reset/', auth_views.PasswordResetView.as_view(
    #     html_email_template_name='registration/password_reset_email.html'
    # )),

    path('accounts/', include('django.contrib.auth.urls')),

    path('admin/', admin.site.urls),

    path('', include('main.urls')),

    path('todo/', include('todo.urls')),
    path('quiz/', include('quiz.urls')),
    path('blog/', include('blog.urls')),
    path('shop/', include('shop.urls')),

    path('dash/', include('dashreporting.urls')),
    path('calendar/', include('calendar_app.urls')),

    path('login/', user_login, name="login"),
    path('logout/', user_logout, name="logout"),
    path('signup/', signup, name="signup"),
    # path('signup-done/', signup_done, name="signup_done"),
    path('change-password/', change_password, name="change-password"),

    path('ckeditor/', include('ckeditor_uploader.urls')), #for ckeditor

    # Django Dash Plotly 
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
    

] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT) #For img

blog/urls.py
from django.urls import path
from blog.views import *

# Define app name to call
app_name = "blog"

urlpatterns = [
    path('posts/', posts, name="posts"),
    path('post/<slug:slug>/', post, name='post'),

    path('post-list/', post_list, name="post_list"),
    path('post-create/', post_create, name="post_create"),    
    path('<slug:slug>/update/', post_update, name='post_update'),
    path('<int:id>/delete/', post_delete, name='post_delete'),
]

main/urls.py
from django.urls import path
from main.views import *

handler404 = 'main.views.handler404'

# Define app name to call
app_name = "main"

urlpatterns = [
    path('', home, name="home"),
    path('home/', home, name="home"),
    path('dashboard/', dashboard, name="dashboard"),
    path('settings/', settings, name="settings"),
    path('profile/', profile, name="profile"),
    path('contact/', contact, name="contact"),
]

quiz/urls.py
from django.urls import path
from quiz.views import *

# Define app name to call
app_name = "quiz"

urlpatterns = [
    path('subject-list/', subject_list, name="subject_list"),
    path('subject/<int:id>/update/', subject_update, name='subject_update'),
    path('subject/<int:id>/delete/', subject_delete, name='subject_delete'),
    path('subject-create/', subject_create, name="subject_create"),

    path('topic/<int:id>/update/', topic_update, name='topic_update'),
    path('topic/<int:id>/delete/', topic_delete, name='topic_delete'),
    path('topic-create/', topic_create, name="topic_create"),

    path('question-list/', question_list, name="question_list"),
    
    path('question-create/', question_create, name="question_create"),
    path('question/<int:id>/update/', question_update, name='question_update'),
    path('question/<int:id>/delete/', question_delete, name='question_delete'),
    path('question/', question, name="question"),

    path('quiz-list/', quiz_list, name="quiz_list"),
    path('quiz/<int:id>/', quiz, name="quiz"),
    path('quiz/<int:id>/update/', quiz_update, name='quiz_update'),
    path('quiz/<int:id>/delete/', quiz_delete, name='quiz_delete'),
    path('quiz-create/', quiz_create, name="quiz_create"),

    path('add-to-quiz/<int:id>/', add_to_quiz, name="add_to_quiz"),

    path('my-quizzes/', my_quizzes, name="my_quizzes"),
    path('my-quiz/<int:id>/', my_quiz, name="my_quiz"),     
    #=============== QUIZs AJAX REQUEST =====================
    path('quiz_test_action/', quiz_test_action, name="quiz_test_action"),
    path('get-topics-ajax/', get_topics_ajax, name="get_topics_ajax"),

    path('quizzes/', quizzes, name="quizzes"),
    path('quiz-start/<int:id>/', quiz_start, name="quiz_start"),
    path('quiz-test/<int:id>/', quiz_test, name="quiz_test"),
    path('quiz-result/<int:id>/', quiz_result, name="quiz_result"),
]

shop/urls.py
from django.urls import path
from shop.views import *

# Define app name to call
app_name = "shop"

urlpatterns = [
    path('products/', products, name="products"),
    path('product/<slug:slug>/', product, name='product'),

    path('product-list/', product_list, name="product_list"),
    path('product-create/', product_create, name="product_create"),    
    path('product/<slug:slug>/update/', product_update, name='product_update'),
    path('product/<int:id>/delete/', product_delete, name='product_delete'),

    path('gallery/<int:id>/delete/', gallery_delete, name='gallery_delete'),
    path('gallery-create/', gallery_create, name='gallery_create'),

    path('category-list/', category_list, name="category_list"),
    path('category/<int:id>/delete/', category_delete, name='category_delete'),
    path('category/<int:id>/update/', category_update, name='category_update'),

    path('shopcart/', shop_cart_list, name='shopcart'),
    path('add-to-cart/<int:id>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<int:id>/', remove_from_cart, name='remove_from_cart'),

    path('checkout/', checkout, name='checkout'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>djangorocket.com</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Favicon icon -->
  <link rel="icon" href="{% static 'logo_head.png' %}" type="image/x-icon">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'assets/plugins/fontawesome-free/css/all.min.css' %} ">
  <!-- Ionicons -->
  <link rel="stylesheet" href=" {% static 'assets/dist/css/ionicons.min.css' %} ">
  <!-- Toastr -->
  <link rel="stylesheet" href="{% static 'assets/plugins/toastr/toastr.min.css' %} ">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'assets/dist/css/adminlte.min.css' %} ">
  <!-- iCheck for checkboxes and radio inputs -->
  <link rel="stylesheet" href="{% static 'assets/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- Custom CSS -->
  <link rel="stylesheet" href="{% static 'assets/custom.css' %} ">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  {% block css %}
  {% endblock css %}
</head>
{% if not user.is_authenticated %}
  <body class="hold-transition layout-top-nav ">
{% else %}
  <body class="hold-transition sidebar-mini ">
{% endif %}
<!-- Site wrapper -->
<div class="wrapper">
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
      </li>
      {% endif %}
      {% if not user.is_authenticated %}
      <a href="{%  url 'main:home' %}" class="brand-link">
        <img src="{% static 'logo.png' %}  "
             alt="Django Rocket Logo"
             class="brand-image"
            >
      </a> 
      {% endif %}
      <!-- to show active link -->
      {% with url_name=request.resolver_match.url_name %}  
        <li class="nav-item d-none d-sm-inline-block">
          <a href="{%  url 'main:home' %}" class="nav-link {% if url_name == 'home' %}active{% endif %}">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
          <a href="{%  url 'blog:posts' %}" class="nav-link {% if url_name == 'posts' %}active{% endif %}">Blog</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
          <a href="{%  url 'shop:products' %}" class="nav-link {% if url_name == 'products' %}active{% endif %}">Shop</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
          <a href="{%  url 'quiz:quizzes' %}" class="nav-link {% if url_name == 'quizzes' %}active{% endif %}">Quiz</a>
        </li>
        <li class="nav-item dropdown">
          <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle">Dash Plotly</a>
          <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
            <li><a href="{%  url 'dashreporting:dash_demo_one' %}" class="dropdown-item">Reporting 1 </a></li>
            <li><a href="{%  url 'dashreporting:dash_demo_four' %}" class="dropdown-item">Sales Analysis</a></li>
          </ul>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
          <a href="{%  url 'main:contact' %}" class="nav-link {% if url_name == 'contact' %}active{% endif %}">Contact</a>
        </li>
      {% endwith %} 
    </ul>
    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      {% if user.is_authenticated %}
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" href="{%  url 'shop:shopcart' %}">
          <i class="fas fa-shopping-cart"></i>
          <span class="badge badge-primary navbar-badge">{{cart_count}}</span>
        </a>
      </li>
      {% endif %} 
      <!-- Actions Dropdown Menu -->
      {% if user.is_authenticated %}
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          {% if user.profile.image %}
            <img src="{{user.profile.image.url}}" width="30px" class="img-size-30 img-circle mr-1" alt="User-Profile-Image"> 
          {% else %}
            <img src="{% static 'avatar_1x.png' %}" width="30px" class="img-size-30 img-circle mr-1" alt="User-Profile-Image">
          {% endif %}            
          {{user.username}}
          <i class="right fas fa-angle-down"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="{%  url 'main:profile' %}" class="dropdown-item">
            <i class="fas fa-user mr-2"></i> Profile
          </a>
          <div class="dropdown-divider"></div>
          <a href="{%  url 'quiz:my_quizzes' %}" class="dropdown-item">
            <i class="fas fa-copy mr-2"></i> My quizzes
          </a>
          <div class="dropdown-divider"></div>
          <a href="{%  url 'logout' %}" class="dropdown-item">
            <i class="fas fa-bell mr-2"></i> Logout
          </a>
        </div>
      </li>
      {% else %}
      <a href="{%  url 'login' %}" class="btn btn-block btn-outline-secondary btn-flat btn-login">LOGIN</a>
      {% endif %} 
    </ul>
  </nav>
  <!-- /.navbar -->
  {% if user.is_authenticated %}
    {% include 'sidebar.html' %}
  {% endif %}

  {% if messages %}
    <div class="content-wrapper custom-alert">
        {% for message in messages %}
          {% if message.tags == 'success' %}
          <div class="callout callout-success custom-callout-success">     
            <p>{{ message }}</p>
          </div>
          {% endif %}
          {% if message.tags == 'warning' %}
            <div class="callout custom-callout custom-callout-warning">     
              <p>{{ message }}</p>
            </div>       
          {% endif %}
        {% endfor %}
    </div>
  {% endif %}
  <!-- Content Wrapper. Contains page content -->
  {% block content %}

  {% endblock content %}
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="float-right d-none d-sm-block">
      <b>Version</b> 1.1.0
    </div>
    <strong>Copyright &copy; 2020 <a href="http:\\etemkeskin.com">etemkeskin.com</a>.</strong> All rights
    reserved.
  </footer>
  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->
<!-- jQuery -->
<script src="{% static 'assets/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'assets/plugins/bootstrap/js/bootstrap.bundle.min.js' %} "></script>
<!-- jQuery UI -->
<script src="{% static 'assets/plugins/jquery-ui/jquery-ui.min.js' %} "></script>
<!-- Toastr -->
<script src="{% static 'assets/plugins/toastr/toastr.min.js' %} "></script>
<!-- AdminLTE App -->
<script src="{% static 'assets/dist/js/adminlte.min.js' %} "></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'assets/dist/js/demo.js' %} "></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-S45S8L010J"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-S45S8L010J');
</script>
{% block javascript %}
    
{% endblock javascript %}
</body>
</html>

templates/sidebar.html
{% load static %}
  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{%  url 'main:home' %}" class="brand-link">
      <img src="{% static 'logo_head.png' %}" style="margin-top: 2px;"
           alt="Django Rocket Logo"
           class="brand-image">
      <span class="brand-text"><img src="{% static 'logo_tail.png' %}" style="margin-left:-10px;" alt="Django Rocket Logo"></span><strong><small>BETA</small> </strong>
    </a>   
    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          {% if user.profile.image %}
            <img src="{{user.profile.image.url}}" width="30px" class="img-size-30 img-circle mr-1" alt="User-Profile-Image"> 
          {% else %}
            <img src="{% static 'assets/dist/img/user2-160x160.jpg' %}" width="30px" class="img-size-30 img-circle mr-1" alt="User-Profile-Image">
          {% endif %}            
        </div>
        <div class="info">
          <a href="{%  url 'main:profile' %}" class="d-block">{{user.username}}</a>
        </div>
      </div>
      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Dash Reporting
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{%  url 'dashreporting:dash_demo_one' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Reporting 1</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{%  url 'dashreporting:dash_demo_four' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Sales Analysis</p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-copy"></i>
              <p>
                Quiz
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{%  url 'quiz:subject_list' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Subjects</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{%  url 'quiz:quiz_list' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Quiz List</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{%  url 'quiz:question_list' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Questions</p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-blog"></i>
              <p>
                Blog
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">             
              <li class="nav-item">
                <a href="{%  url 'blog:post_list' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Post List</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{%  url 'blog:post_create' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Add New Post</p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-cart-plus"></i>
              <p>
                Shop
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{%  url 'shop:category_list' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Categories</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{%  url 'shop:product_list' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Products</p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <a href="{%  url 'calendar_app:calendar' %}" class="nav-link">
              <i class="nav-icon fas fa-calendar-alt"></i>
              <p>
                Calendar
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{%  url 'todo:todo_list' %}" class="nav-link">
              <i class="nav-icon fas fa-bookmark"></i>
              <p>
                Todo
              </p>
            </a>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>
  